### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by TonyFeestneus** [NovaGL/homebridge-http-advanced#2]
I get this error after installing it:

[10/29/2016, 3:40:45 PM] ====================
[10/29/2016, 3:40:45 PM] ERROR LOADING PLUGIN homebridge-http-advanced:
[10/29/2016, 3:40:45 PM] Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-http-advanced/index.js:2:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[10/29/2016, 3:40:45 PM] ====================

what is the problem here?

**Comment by NovaGL** [comment]
`Cannot find module 'request'`

After you cloned the repo you need to do npm install which will download the dependencies such as request. I will have to modify the readme when I get a chance. Let me know if that works

**Comment by TonyFeestneus** [comment]
npm install homebridge-http-advanced or just npm install?

**Comment by NovaGL** [comment]
If you are in the folder npm install should be fine
