### ISSUE TITLE
parsing error when trying to poll status 

### ISSUE THREAD

**Issue by webpablo** [NovaGL/homebridge-http-advanced#7]
I apologize but I am working at the outer ends of my comfort zone. 

Overview: 
I am using an Arduino Wifi Uno to handle requests to open and close an actuator. I have it working so that the status 1 or 0 outputs to a URL as a standard HTML page. When I use that URL as my status URL it constantly fails, though if I visit the page in the browser I get a very clear 1 or 0. Should I be formatting my response differently from the around? I can structure it however needed. 

Here is the response from the ardunio as viewed from the browser. 
<html>
<head> </head>
<body>0</body></html>
<!--~--

The error I am seeing is:
[6/4/2017, 9:37:44 PM] [SkyLight] Light received data:http://10.0.1.205/arduino/webserver state is currently NaN
[6/4/2017, 9:37:44 PM] [SkyLight] Setting power state to off
[6/4/2017, 9:37:47 PM] [SkyLight] HTTP get power function failed: Parse Error
/usr/local/lib/node_modules/homebridge-http/index.js:60
		                callback(error);
		                ^

ReferenceError: callback is not defined
    at /usr/local/lib/node_modules/homebridge-http/index.js:60:19
    at Request._callback (/usr/local/lib/node_modules/homebridge-http/index.js:160:4)
    at self.callback (/usr/local/lib/node_modules/homebridge-http/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-http/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketOnData (_http_client.js:416:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)

**Comment by NovaGL** [comment]
What does the homebridge log show

**Comment by webpablo** [comment]
Oh weird, the original post got truncated rather badly. Here is the HTML response from the ardunio
`<html>`
`<head>` </head>
`<body>0</body></html>`
`<!--~--`

Here is the homebridge log 
`[6/5/2017,` 9:43:44 AM] [SkyLight] Light received data:http://10.0.1.205/arduino/webserver state is `currently` NaN
`[6/5/2017,` 9:43:44 AM] [SkyLight] Setting power state to off
`[6/5/2017,` 9:43:45 AM] [Broadlink RM] Rear shade setCurrentPosition: 100
`[6/5/2017,` 9:43:45 AM] [Broadlink RM] Rear shade setCurrentPosition: already 100
`[6/5/2017,` 9:43:45 AM] [Broadlink RM] Rear shade setPositionState: 2
`[6/5/2017,` 9:43:45 AM] [Broadlink RM] Rear shade setPositionState: already 2
`[6/5/2017,` 9:43:45 AM] [Broadlink RM] Rear shade setTargetPosition: 100
`[6/5/2017,` 9:43:45 AM] [Broadlink RM] Rear shade setTargetPosition: already 100
[6/5/2017, 9:43:46 AM] [SkyLight] HTTP get power function failed: Parse Error
/usr/local/lib/node_modules/homebridge-http/index.js:60
		                callback(error);
		                ^

ReferenceError: callback is not defined
    at /usr/local/lib/node_modules/homebridge-http/index.js:60:19
    at Request._callback (/usr/local/lib/node_modules/homebridge-http/index.js:160:4)
    at self.callback (/usr/local/lib/node_modules/homebridge-http/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-http/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketOnData (_http_client.js:416:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
`

**Comment by NovaGL** [comment]
Thanks for that.

How does your config look? Hide the personal info

**Comment by webpablo** [comment]
{
  "bridge":{
    "name":"Homebridge",
    "username":"XXXXXXXXXX",
    "port":XXXX,
    "pin":"XXXX"
  },
  "description":"Homebridge",
  "accessories":[
    {
      "accessory": "Http-advanced",
         	"name": "SkyLight",
         	"switchHandling": "realtime",
         	"http_method": "GET",
          "on_url":      "http://10.0.1.205/arduino/digital/5/0",
          "off_url":     "http://10.0.1.205/arduino/digital/6/0",
           "status_url":  "http://10.0.1.205/arduino/webserver",
         	"service": "Light",
         	"sendimmediately": "",
         	"username" : "",
         	"password" : ""

     }

  ],
  "platforms":[

    {
    "platform": "IFTTT",
    "name": "IFTTT",
    "makerkey": "XXXXXXX",
    "accessories": [{
            "name": "Accessory 1",
            "buttons": [
              {
                "caption": "Ford's Blinds",
                "triggerOn": "Ford-GoodMorning",
                "triggerOff": "Ford-GoodNight"

              },
              {
                "caption": "NA",
                "triggerOn": "XXXXX",
                "triggerOff": "XXXXXX"

              }
            ]
      }

    ]
  },

    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "accessories":[

        {
                 "name":"Rear shade",
                 "type":"window-covering",
                 "host":"XXXXXXXXXXX",
                 "totalDurationOpen": 21,
                 "totalDurationClose": 21,
                 "data":{
                   "open":"XXXXXX",
                   "close":"XXXXX",
                  "stop":"XXXXX"

                 }
               }





      ]
    }
  ]


}

**Comment by NovaGL** [comment]
Maybe it doesn't like all that other text. Can you get it just to output 0?

So it doesn't say head etc

**Comment by webpablo** [comment]
Finally got around to trying this after some travel. The request just times out if All I do is output an unformatted 0 response.

**Comment by NovaGL** [comment]
Not sure what's going on.
So simple off and on work?

What if you put a file on your websever and just have 0 in it and use that for the state see if that works.

Alternatively homebridge-http was recently updated and maybe one of the pull releases there fixes your problem.

**Comment by webpablo** [comment]
I am actually running homebridge-http as we speak and seeing the same thing. Without status URL on and off work fine.

**Comment by webpablo** [comment]
I am sure it's expecting a certain type of response. Either a Json item or an HTTP response formatted in a certain way. I just don't know what it wants so I can't make the arduino spit it out. =/

**Comment by webpablo** [comment]
oh interesting, Looks like there was an open issue on the other http plugin that is the same as I was seeing. I am not getting SOME response, but things aren't playing right. Ill open a fresh issue thats more clear for what I am seeing now. We can close this particular one for now. 

for future reference if anyone finds this, the response looks like this 
`client.println("HTTP/1.1 200 OK");`
`client.println("Content-Type: text/html");`
`client.println("Connnection: close");`
`client.println();`
`client.println(skylightStatus); // for on and 0 for off.`
`delay(1);`
`client.print(DELIMITER);`
