### ISSUE TITLE
Not working on MOTION

### ISSUE THREAD

**Issue by greensouth** [NovaGL/homebridge-http-advanced#8]
Maybe i'm dumb but can't make it work when changing "light" to "Motion"

get this:

TypeError: Cannot read property '0' of undefined
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:380:17)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by NovaGL** [comment]
You have to give me more information.

What does your JSON setup look like.

Does the HTTP response just have a zero or one. Unfortunately this repo requires a very specific response.

You could also give Occupancy a go, does light work?
