### ISSUE TITLE
Status error

### ISSUE THREAD

**Issue by batizisanya** [NovaGL/homebridge-http-advanced#9]
I get this error sometimes. Can you (or someone) correct this. Like if its can't get the status, wait X seconds and than try again, or something. 

[9/19/2017, 9:50:50 PM] [led] HTTP get power function failed: socket hang up
/usr/lib/node_modules/homebridge-http/index.js:60
                                callback(error);
                                ^

ReferenceError: callback is not defined
    at /usr/lib/node_modules/homebridge-http/index.js:60:19
    at Request._callback (/usr/lib/node_modules/homebridge-http/index.js:160:4)
    at self.callback (/usr/lib/node_modules/homebridge-http/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-http/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:345:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)

**Comment by NovaGL** [comment]
I believe this is a bit outside my ability but I will leave it open if anyone comes around and knows how to solve it.

**Comment by jubudu** [comment]
I get the same error, several times a day! It seems to be a time out error due to low wifi reception of my http-switch downstairs.
I attached a screenshot of my error report.

![img_1867](https://user-images.githubusercontent.com/11777741/30885684-8390763e-a314-11e7-80cc-246270467e92.jpg)
